version: 2

sources:
    -   name: classicmodels
        description: The main database containing all our data.
        tables:
            -   name: customers
            -   name: employees
            -   name: offices
            -   name: orderdetails
            -   name: orders
            -   name: payments
            -   name: productlines
            -   name: products